### ISSUE TITLE
Configuration validation fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by wanderanimrod** [jradtilbrook/ansible-role-metricbeat#1]
Hello,

Thanks for providing this role. 

I have just gave it a few test runs on Ubuntu 14.04 and it fails when trying at this task `copy metricbeat configuration`. Specifically, it fails to validate the metricbeats config using this code `validate: /usr/bin/metricbeat.sh -c %s -configtest` when running the task as root in my playbook.

The error ansible throws is below. 

> {"changed": true, "exit_status": 1, "failed": true, "msg": "failed to validate", "stderr": "metricbeat2017/08/12 08:54:53.474024 beat.go:339: CRIT Exiting: error loading config file: config file (\"/home/ubuntu/.ansible/tmp/ansible-tmp-1502528219.4-28975408851694/source\") must be owned by the beat user (uid=0) or root\nExiting: error loading config file: config file (\"/home/ubuntu/.ansible/tmp/ansible-tmp-1502528219.4-28975408851694/source\") must be owned by the beat user (uid=0) or root\n", "stdout": "", "stdout_lines": []}

I have so far failed to understand where the error is coming from because when I try to validate the template on the box using the same command, the validation passes. If I had to guess, I would say it has something to do with the ansible process not having access to either the `metricbeat.sh` file or another file metricbeat needs to run the validation.

I have temporarily forked the repo and commented out failing line and everything works fine. Am I missing something obvious?

Thanks.

**Comment by jradtilbrook** [comment]
Hi. Thanks for letting me know of this issue.  
It looks to me like a combination of things:

1. The role will be installing the newest version of Filebeat for which file permissions checks have been added.
2. Ansible doesn't honour the the same permissions specified when creating the temporary file it runs the validation against. I have had this issue before and I believe it might be an ongoing issue.

However I'm not really sure why its failing - I have re-run the Travis build and it passed successfully.

Can you let me know what version of Ansible you are running? I would prefer not to just remove that line since its quite important to ensure the config is valid - although the restart step should fail if it is invalid anyway.

**Comment by wanderanimrod** [comment]
Thank you for getting back quickly.

`ansible 2.2.0.0`

>I would prefer not to just remove that line since its quite important to ensure the config is valid - although the restart step should fail if it is invalid anyway.

It think this is a good idea. The service will fail to start anyway. It's a simple change for you to implement but if you'd like to get the first pull request, I can send one 😄

**Comment by jradtilbrook** [comment]
Resolved in #2
